// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProductSearchMicroservice.Infrastructure.ApplicationDbContext;

#nullable disable

namespace ProductSearchMicroservice.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250610233133_DataSeeding")]
    partial class DataSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProductSearchMicroservice.Domain.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Café de origen colombiano.",
                            Name = "Café Premium",
                            Price = 4.9900000000000002
                        },
                        new
                        {
                            Id = 2,
                            Description = "Bluetooth 5.0 y cancelación de ruido.",
                            Name = "Auriculares Inalámbricos",
                            Price = 24.989999999999998
                        },
                        new
                        {
                            Id = 3,
                            Description = "Switches rojos y retroiluminación RGB.",
                            Name = "Teclado Mecánico",
                            Price = 59.990000000000002
                        },
                        new
                        {
                            Id = 4,
                            Description = "Diseño lumbar para largas jornadas.",
                            Name = "Silla Ergonómica",
                            Price = 129.99000000000001
                        },
                        new
                        {
                            Id = 5,
                            Description = "Luz blanca cálida y fría con sensor táctil.",
                            Name = "Lámpara LED",
                            Price = 15.99
                        },
                        new
                        {
                            Id = 6,
                            Description = "8GB RAM, 256GB SSD, Ryzen 5.",
                            Name = "Notebook 15.6\"",
                            Price = 499.99000000000001
                        },
                        new
                        {
                            Id = 7,
                            Description = "Compartimientos secretos y USB externo.",
                            Name = "Mochila Antirrobo",
                            Price = 34.899999999999999
                        },
                        new
                        {
                            Id = 8,
                            Description = "Carga rápida con doble salida.",
                            Name = "Batería Portátil 10000mAh",
                            Price = 22.5
                        },
                        new
                        {
                            Id = 9,
                            Description = "Mantiene frío o calor por 12 horas.",
                            Name = "Botella Térmica",
                            Price = 18.699999999999999
                        },
                        new
                        {
                            Id = 10,
                            Description = "Sensor óptico 7200 DPI con RGB.",
                            Name = "Mouse Gamer",
                            Price = 29.989999999999998
                        },
                        new
                        {
                            Id = 11,
                            Description = "De Robert C. Martin.",
                            Name = "Libro: Clean Architecture",
                            Price = 39.0
                        },
                        new
                        {
                            Id = 12,
                            Description = "Mayor velocidad y cobertura.",
                            Name = "Router Wi-Fi 6",
                            Price = 89.0
                        },
                        new
                        {
                            Id = 13,
                            Description = "Ideal para leer y consumir contenido.",
                            Name = "Tablet 10\"",
                            Price = 189.99000000000001
                        },
                        new
                        {
                            Id = 14,
                            Description = "Perfecta para videollamadas.",
                            Name = "Cámara Web HD",
                            Price = 49.899999999999999
                        },
                        new
                        {
                            Id = 15,
                            Description = "USB 3.0 de alta velocidad.",
                            Name = "Disco Duro Externo 1TB",
                            Price = 65.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
